alldata <- read.csv("household_power_consumption.txt",sep =";", stringsAsFactors = FALSE)
alldata$newdate <- with(alldata, as.POSIXct(paste(Date, Time), format="%d/%m/%Y %H:%M"))
graphdata <- subset(alldata,newdate >= "2007-02-01" & newdate < "2007-02-03")
graphdata$Sub_metering_1 <- as.numeric(graphdata$Sub_metering_1)
graphdata$Sub_metering_2 <- as.numeric(graphdata$Sub_metering_2)
graphdata$Sub_metering_3 <- as.numeric(graphdata$Sub_metering_3)
graphdata <- subset(graphdata, !is.na(Sub_metering_1))
graphdata <- subset(graphdata, !is.na(Sub_metering_2))
graphdata <- subset(graphdata, !is.na(Sub_metering_3))
png(filename="Plot3.png")
with(graphdata, plot(newdate, Sub_metering_1, type = "l", main = "", ylab ="Energy sub metering", xlab =""))
with(graphdata, points(newdate, Sub_metering_2, type = "l", col="red" ))
with(graphdata, points(newdate, Sub_metering_3, type = "l", col="blue" ))
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),
       col=c("black","red", "blue"), lty=1:2, cex=0.8)
dev.off()